version: '3.3'
services:
  celebi:
    build:
      context: ../
      dockerfile: ./Docker/Dockerfile
    ports:
     - "18964:8964"
  postgres:
    image: postgres:latest
  grafana:
    image: grafana:latest
