version: '3.3'
services:
  postgres:
    image: "postgres"
  grafana:
    image: "grafana/grafana"
  rabbitmq:
    image: "rabbitmq"
  celebi:
    build:
      context: "../"
      dockerfile: "./Docker/Dockerfile"
    ports:
     - "18964:8964"
    depends_on:
      - "postgres"
      - "rabbitmq"
    links:
      - postgres
      - grafana
      - rabbitmq
